default_sched = "scx_lavd"
default_mode = "PowerSave"

[scheds.scx_lavd]
# ACPI highest_perf: 4,6 (208); 0,8 (202); 2,10 (196); SMT siblings (135)
auto_mode = [
    "--autopower",
    "--cpu-pref-order", "4,6,0,2,1,3,5,7,12,14,8,10,9,11,13,15",
    "--lb-low-util-pct", "15"
]
gaming_mode = [
    "--performance",
    "--cpu-pref-order", "4,6,0,2,12,14,8,10,1,3,5,7,9,11,13,15",
    "--lb-low-util-pct", "0"
]
balanced_mode = [
    "--balanced",
    "--cpu-pref-order", "4,6,0,2,1,3,5,7,12,14,8,10,9,11,13,15",
    "--lb-low-util-pct", "25"
]
powersave_mode = [
    "--powersave",
    "--cpu-pref-order", "1,3,5,7,9,11,13,15,4,6,0,2,12,14,8,10",
    "--lb-low-util-pct", "85"
]
lowlatency_mode = []
server_mode = []
